# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scoreMO <- function(alpha, Y, X, Q, q, n, I, pall, pX, pXRS, pthresh, pshift, prnd, GHweights, GHnodes, scaled, dthresh, cores, lambda) {
    .Call(`_MultOrdRS_scoreMO`, alpha, Y, X, Q, q, n, I, pall, pX, pXRS, pthresh, pshift, prnd, GHweights, GHnodes, scaled, dthresh, cores, lambda)
}

loglikMO <- function(alpha, Y, X, Q, q, n, I, pall, pX, pXRS, pthresh, pshift, prnd, GHweights, GHnodes, scaled, dthresh, cores, lambda) {
    .Call(`_MultOrdRS_loglikMO`, alpha, Y, X, Q, q, n, I, pall, pX, pXRS, pthresh, pshift, prnd, GHweights, GHnodes, scaled, dthresh, cores, lambda)
}

loglikMO_noRS <- function(alpha, Y, X, Q, q, n, I, pall, pX, pthresh, pshift, GHweights, GHnodes, dthresh, cores, lambda) {
    .Call(`_MultOrdRS_loglikMO_noRS`, alpha, Y, X, Q, q, n, I, pall, pX, pthresh, pshift, GHweights, GHnodes, dthresh, cores, lambda)
}

scoreMO_noRS <- function(alpha, Y, X, Q, q, n, I, pall, pX, pthresh, pshift, GHweights, GHnodes, dthresh, cores, lambda) {
    .Call(`_MultOrdRS_scoreMO_noRS`, alpha, Y, X, Q, q, n, I, pall, pX, pthresh, pshift, GHweights, GHnodes, dthresh, cores, lambda)
}

loglikMO_cumul <- function(alpha, Y, X, Q, q, n, I, pall, pX, pXRS, pthresh, pshift, prnd, GHweights, GHnodes, scaled, cores, lambda) {
    .Call(`_MultOrdRS_loglikMO_cumul`, alpha, Y, X, Q, q, n, I, pall, pX, pXRS, pthresh, pshift, prnd, GHweights, GHnodes, scaled, cores, lambda)
}

loglikMO_cumul_noRS <- function(alpha, Y, X, Q, q, n, I, pall, pX, pthresh, pshift, prnd, GHweights, GHnodes, scaled, cores, lambda) {
    .Call(`_MultOrdRS_loglikMO_cumul_noRS`, alpha, Y, X, Q, q, n, I, pall, pX, pthresh, pshift, prnd, GHweights, GHnodes, scaled, cores, lambda)
}

